### ISSUE TITLE
运行不起来

### ISSUE THREAD

**Issue by 73hulu** [linchuming/LyingMan#2]
我已经开启了nodejs
![image](https://cloud.githubusercontent.com/assets/6497213/26517860/4c875f5e-42d4-11e7-91b3-10d8ea6cae4f.png)，但是运行出现
![image](https://cloud.githubusercontent.com/assets/6497213/26517861/55f9f84e-42d4-11e7-8444-6ed0710390b6.png)

**Comment by linchuming** [comment]
因为你是在server路径下执行的，这样它的__dirname指向的是server路径，我们的网页部分是写在web文件夹的，所以你需要在LyingMan的目录下直接执行 node server ，不要在server路径下执行。
另外就是我们这个是一个课程项目，非正式项目，里面有部分功能是没有实现的，例如用户断线了怎么重新连回来，如果有兴趣欢迎补充23333

**Comment by zsydyc** [comment]
我能够运行 不过在最开始填写用户名之后  无论选择线下还是线上  都让我输入房间号  输入房间后点确定没有反应
请问是怎么回事？
  


---看了下你代码 懂了 房间名需要4位数字

**Comment by linchuming** [comment]
@zsydyc emmm，我对外文档确实没说这个，好的我补充上了，谢谢= =
